// Regenerates tokens.css (from tokens.json) and index.html (the gallery of
// component previews and icons). Run after editing tokens.json or adding a
// component, icon or preview:  node design-system/build.mjs
import { readFileSync, readdirSync, writeFileSync, existsSync } from 'node:fs';

const dir = new URL('.', import.meta.url);
const read = path => readFileSync(new URL(path, dir), 'utf8');
const esc = s => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

// ── tokens.css ──────────────────────────────────────────────────────────────
const tokens = JSON.parse(read('tokens.json'));
const [primary, ...others] = tokens.color.themes.map(t => t.id);

const value = v => {
  const alias = /^\{(.+)\}$/.exec(v);
  return alias ? `var(--${alias[1]})` : v;
};
const decls = (list, theme) =>
  list
    .map(t => {
      const v = typeof t.value === 'object' ? t.value[theme] : theme === primary ? t.value : undefined;
      return v === undefined ? null : `  --${t.name}: ${value(v)};`;
    })
    .filter(Boolean)
    .join('\n');

const fontFaces = tokens.type.fonts
  .map(f => `@font-face {\n  font-family: "${f.family}";\n  src: url("${f.file}") format("woff2");\n  font-weight: ${f.weight};\n  font-style: ${f.style ?? 'normal'};\n  font-display: swap;\n}`)
  .join('\n');
const families = Object.entries(tokens.type.families)
  .map(([k, v]) => `  --font-${k}: ${v};`)
  .join('\n');
const lengths = ['spacing', 'radius']
  .flatMap(k => tokens[k]?.tokens ?? [])
  .map(t => `  --${t.name}: ${t.value};`)
  .join('\n');

writeFileSync(
  new URL('tokens.css', dir),
  `/* ${tokens.name} — generated from tokens.json by build.mjs; don't edit. */
${fontFaces}

:root {
${families}
${lengths}
${decls(tokens.color.tokens, primary)}
}
${others
  .map(theme => `\n:root[data-theme="${theme}"] {\n  color-scheme: ${theme};\n${decls(tokens.color.tokens, theme)}\n}`)
  .join('\n')}
`,
);

// ── index.html ──────────────────────────────────────────────────────────────
const groupOrder = ['Navigation', 'Content', 'Lists', 'Actions', 'Sheets', 'Forms', 'Feedback'];
const cards = readdirSync(new URL('components/', dir), { withFileTypes: true })
  .filter(d => d.isDirectory() && d.name !== 'Cover' && existsSync(new URL(`components/${d.name}/preview.html`, dir)))
  .map(d => {
    const meta = /@dsCard(?:\s+group="([^"]+)")?\s+height=(\d+)/.exec(read(`components/${d.name}/preview.html`));
    const readme = existsSync(new URL(`components/${d.name}/README.md`, dir)) ? read(`components/${d.name}/README.md`) : '';
    const summary = readme.split('\n').find(l => l.trim() && !l.startsWith('#')) ?? '';
    return { name: d.name, group: meta?.[1] ?? 'Other', height: Number(meta?.[2] ?? 300), summary };
  });
const groups = [...new Set([...groupOrder, ...cards.map(c => c.group)])].filter(g => cards.some(c => c.group === g));
const icons = readdirSync(new URL('assets/Icons/', dir)).filter(f => f.endsWith('.svg'));

const card = c => `
      <article class="card" id="${c.name}">
        <header><h3>${c.name}</h3><a href="components/${c.name}/README.md">Guidelines</a></header>
        <p>${esc(c.summary).replace(/`([^`]+)`/g, '<code>$1</code>')}</p>
        <iframe src="components/${c.name}/preview.html" data-src="components/${c.name}/preview.html" height="${c.height}" loading="lazy" title="${c.name} preview"></iframe>
      </article>`;

writeFileSync(
  new URL('index.html', dir),
  `<!doctype html>
<!-- Generated by build.mjs; don't edit. -->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Portifo design system</title>
<link rel="icon" href="assets/Logos/app-icon.png">
<link rel="stylesheet" href="tokens.css">
<style>
  * { box-sizing: border-box; }
  body { margin: 0; background: var(--ds-subtle); color: var(--ds-text); font-family: var(--font-body); -webkit-font-smoothing: antialiased; }
  .top { position: sticky; top: 0; z-index: 1; display: flex; gap: 16px; align-items: center; flex-wrap: wrap; padding: 14px 24px; background: var(--ds-bg); box-shadow: inset 0 -1px var(--ds-line); }
  .top h1 { margin: 0 auto 0 0; font: 650 20px/1.2 var(--font-display); letter-spacing: -0.5px; display: flex; gap: 10px; align-items: center; }
  .top h1 img { width: 26px; height: 26px; border-radius: 6px; }
  .top nav { display: flex; gap: 14px; flex-wrap: wrap; font-size: 13px; }
  a { color: var(--ds-accent); text-decoration: none; }
  a:hover { text-decoration: underline; }
  .theme { display: flex; gap: 2px; padding: 2px; border-radius: 8px; background: var(--ds-subtle); }
  .theme button { font: inherit; font-size: 12px; border: 0; padding: 6px 12px; border-radius: 6px; background: none; color: var(--ds-secondary); cursor: pointer; }
  .theme button[aria-pressed="true"] { background: var(--ds-bg); color: var(--ds-text); }
  main { max-width: 1320px; margin: 0 auto; padding: 8px 24px 64px; }
  h2 { font: 600 22px/1.2 var(--font-display); letter-spacing: -0.5px; margin: 36px 0 14px; }
  .docs { display: flex; gap: 10px; flex-wrap: wrap; font-size: 14px; color: var(--ds-secondary); }
  .docs a { padding: 9px 14px; border-radius: 8px; background: var(--ds-bg); box-shadow: inset 0 0 0 1px var(--ds-line); }
  .card { background: var(--ds-bg); border-radius: 12px; box-shadow: inset 0 0 0 1px var(--ds-line); padding: 16px 16px 0; margin-bottom: 16px; overflow: hidden; }
  .card header { display: flex; justify-content: space-between; align-items: baseline; gap: 12px; }
  .card h3 { margin: 0; font: 600 16px/1.2 var(--font-display); }
  .card header a { font-size: 13px; }
  .card p { margin: 6px 0 14px; font-size: 13px; line-height: 1.6; color: var(--ds-secondary); }
  code { font-family: var(--font-mono); font-size: 0.92em; }
  .card iframe { display: block; width: calc(100% + 32px); margin: 0 -16px; border: 0; border-top: 1px solid var(--ds-line); }
  .icons { display: grid; grid-template-columns: repeat(auto-fill, minmax(120px, 1fr)); gap: 8px; }
  .icons figure { margin: 0; padding: 16px 8px 10px; background: var(--ds-bg); border-radius: 10px; box-shadow: inset 0 0 0 1px var(--ds-line); text-align: center; }
  .icons img { width: 28px; height: 28px; margin: 0 auto 10px; display: block; }
  :root[data-theme="dark"] .icons img { filter: invert(1) hue-rotate(180deg); }
  .icons figcaption { font-family: var(--font-mono); font-size: 10px; color: var(--ds-secondary); overflow-wrap: anywhere; }
  @media (max-width: 600px) { .top, main { padding-inline: 16px; } }
</style>
</head>
<body>
  <div class="top">
    <h1><img src="assets/Logos/app-icon.png" alt="">Portifo design system</h1>
    <nav>${groups.map(g => `<a href="#${g}">${g}</a>`).join('')}<a href="#Icons">Icons</a></nav>
    <div class="theme" role="group" aria-label="Theme"><button type="button" data-theme="light" aria-pressed="true">Light</button><button type="button" data-theme="dark" aria-pressed="false">Dark</button></div>
  </div>
  <main>
    <h2>Read first</h2>
    <div class="docs">
      <a href="README.md">README: principles, writing, colour, type, spacing</a>
      <a href="screen-anatomy.md">Screen anatomy: the four screen kinds</a>
      <a href="tokens.json">tokens.json</a>
    </div>
${groups
  .map(g => `
    <section id="${g}">
      <h2>${g}</h2>${cards.filter(c => c.group === g).map(card).join('')}
    </section>`)
  .join('')}

    <section id="Icons">
      <h2>Icons</h2>
      <div class="icons">${icons.map(f => `<figure><img src="assets/Icons/${f}" alt=""><figcaption>${f.replace('.svg', '')}</figcaption></figure>`).join('')}</div>
    </section>
  </main>
<script>
  const buttons = document.querySelectorAll('.theme button');
  function setTheme(theme) {
    document.documentElement.dataset.theme = theme;
    buttons.forEach(b => b.setAttribute('aria-pressed', String(b.dataset.theme === theme)));
    document.querySelectorAll('iframe[data-src]').forEach(f => { f.src = f.dataset.src + (theme === 'dark' ? '?theme=dark' : ''); });
    try { localStorage.setItem('ds-theme', theme); } catch {}
  }
  buttons.forEach(b => b.addEventListener('click', () => setTheme(b.dataset.theme)));
  addEventListener('message', e => {
    const frame = [...document.querySelectorAll('iframe')].find(f => f.contentWindow === e.source);
    if (frame && e.data?.dsPreviewHeight) frame.height = e.data.dsPreviewHeight;
  });
  try { const saved = localStorage.getItem('ds-theme'); if (saved && saved !== 'light') setTheme(saved); } catch {}
</script>
</body>
</html>
`,
);

console.log(`wrote design-system/tokens.css and index.html (${cards.length} components, ${icons.length} icons)`);
